### ISSUE TITLE
Planet

### ISSUE THREAD

**Issue by TheProBanana** [TheProBanana/springProject2018#5]
- [x] establish constructors which will create 3 planets and assign them the 3 random names from the arrayList

- [x] Data fields : size of circle, color, name, items

- [x] Make getters/setters

- [x] Display planets as objects located randomly in the grid with list of items

- [x] come up with original planet names, not ones in our solar system, so their size and color do not matter

**Comment by TheProBanana** [comment]
Create a list( Button with three lines and a check mark) for items you think should be in this class.

**Comment by Ally8** [comment]
- [ ] establish constructors which will create 3 planets and assign them the 3 random names from the arrayList

- [ ] Data fields : size of circle, color, name, items

- [ ] Make getters/setters

- [ ] Display planets as objects located randomly in the grid with list of items

- [ ] come up with original planet names, not ones in our solar system, so their size and color do not matter
